version: 2

project_name: test-sdk

monorepo:
  tag_prefix: test-sdk/
  dir: packages/test-sdk

gomod:
  proxy: true

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: jameswlane
    name: test-turborepo
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  draft: false
  prerelease: auto